checkpoints/latest:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${run.dir}/checkpoints/
  filename: latest
  every_n_epochs: 1

checkpoints/best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${run.dir}/checkpoints/
  filename: best
  monitor: val/metrics/miou
  mode: max
  every_n_epochs: 1
